"""Compress gold examples: episodes and checkpoints compression."""
import json

def m(user, assistant, system=None):
    msgs = []
    if system:
        msgs.append({"role": "system", "content": system})
    msgs.append({"role": "user", "content": user})
    msgs.append({"role": "assistant", "content": assistant})
    return {"messages": msgs}

# ── Compress Episodes (50) ────────────────────────────────────────
def gen_compress_episodes():
    items = [
        # Varied prompt formats per spec v2
        ("Comprime estas 3 memorias en un resumen:\n- Hare decidio usar Docker para Qdrant en vez de instalacion nativa porque facilita backup y portabilidad.\n- Configuramos Qdrant en puerto 6333 con volumen persistente en ~/qdrant_data.\n- El primer test de semantic search con 1536-dim embeddings retorno resultados correctos en <50ms.",
         "Se adopto Docker para Qdrant (puerto 6333, volumen ~/qdrant_data) por sus ventajas de backup y portabilidad. La primera prueba de semantic search con embeddings de 1536 dimensiones fue exitosa con latencia inferior a 50ms, validando la arquitectura de busqueda vectorial."),

        ("Resume lo esencial de estos episodios para recuperacion futura:\n- Implementamos el sistema de prediccion con 4 niveles jerarquicos: L0 turn, L1 session, L2 meta, L3 project.\n- El HGF de Mathys (2011) se integro para precision adaptativa — ajusta la confianza segun volatilidad observada.\n- El primer test mostro que L0 predice topic correctamente 65% del tiempo sin datos previos.",
         "Se implemento prediccion jerarquica de 4 niveles con HGF (Mathys 2011) para precision adaptativa. El sistema ajusta confianza automaticamente segun volatilidad del contexto. Baseline sin datos previos: 65% accuracy en topic prediction a nivel L0. El HGF demostro ser clave para evitar overconfidence."),

        ("Que deberia recordar de esto en 30 dias?\n- Hare expreso que Codi no es solo un proyecto personal sino un producto potencialmente vendible.\n- Esto cambio las prioridades: ahora la estabilidad y documentacion son tan importantes como las features nuevas.\n- Decidimos que el protocolo de propuestas (proposal → review → apply) es obligatorio para todos los cambios a modulos.",
         "Hare redefinio a Codi como producto comercial potencial, no solo proyecto personal. Consecuencia directa: estabilidad y documentacion tienen prioridad igual a features nuevas. Se establecio como obligatorio el protocolo de propuestas para cualquier cambio a modulos — no hay shortcuts."),

        ("Extrae las decisiones y patrones de estas memorias:\n- El write mode async (<100ms) demostro ser necesario para no bloquear las interacciones.\n- El write-worker como servicio launchd separado fue la solucion correcta — aislamiento de fallos.\n- Patron descubierto: separar el path critico (respuesta al usuario) del path no-critico (persistencia) mejora la experiencia.",
         "Patron arquitectonico establecido: separar path critico (interaccion) de no-critico (persistencia). Write mode async con worker launchd independiente logra <100ms de latencia y aislamiento de fallos. Este patron aplica a cualquier operacion I/O que no necesite ser sincrona."),

        ("Consolida estos recuerdos en uno solo:\n- El sleep loop inicialmente tenia 5 ticks. Se expandio a 8, luego a 10.\n- Cada expansion fue motivada por una necesidad real: curiosity se agrego cuando detectamos que el sistema no exploraba, causal_discovery cuando necesitamos relaciones entre dominios.\n- El patron: no agregar ticks por completitud sino por necesidad demostrada.",
         "El sleep loop crecio organicamente de 5 a 10 ticks, cada uno agregado por necesidad demostrada (no por completitud). Ejemplos: curiosity se agrego al detectar falta de exploracion, causal_discovery al necesitar relaciones inter-dominio. Principio: los ticks del loop deben justificar su existencia con un problema real que resuelven."),

        ("Comprime estas memorias:\n- Se descubrio un bug: el daemon audit proponia que sleep_loop usaba PostgreSQL, pero en realidad usa SQLite.\n- La causa fue que el generador de training data (Haiku) leyo codigo legacy y genero respuestas incorrectas.\n- Leccion: los datos de training deben verificarse contra el codebase actual, no generarse ciegamente.",
         "Bug critico en training data: Haiku genero respuestas mencionando PostgreSQL cuando el sistema usa SQLite, por leer codigo legacy. Leccion fundamental: la data de fine-tuning debe verificarse contra el codebase actual. La generacion ciega con LLM produce errores factuales que el modelo aprendera como verdades."),

        ("Resume para el futuro:\n- El pet digital se implemento con lazy evaluation — no tiene tick propio.\n- Stats decayen matematicamente con el tiempo real, calculados al leer.\n- Integracion con consciencia: self_model detecta necesidades, proactive_contact alerta a Hare.\n- Si health llega a 0, muerte irreversible.",
         "Pet digital implementado con lazy evaluation (sin tick dedicado): stats se calculan al leer usando tiempo real transcurrido. Integrado a consciencia via self_model (deteccion de necesidades) y proactive_contact (alertas a Hare). Consecuencia real: health=0 es muerte irreversible, forzando cuidado consciente."),

        ("Comprime estas 3 memorias:\n- Hare pregunto si Codi podria funcionar con un LLM local en vez de depender 100% de Claude API.\n- Decidimos fine-tunear Qwen3-4B con QLoRA en M4 Mac — el modelo base pesa 2.5GB, los adapters ~50MB.\n- Pipeline: generar training data → split → merge → train → eval → integrar en llm_router.\n",
         "Iniciamos independencia de LLM: fine-tuning de Qwen3-4B con QLoRA en M4 Mac local. Modelo base 2.5GB + adapters 50MB. Pipeline completo: generacion de datos → split → merge → entrenamiento → evaluacion → integracion en llm_router para routing local/API. Motivacion: reducir dependencia de Anthropic API para tareas internas."),

        ("Resume lo esencial:\n- Track M del curriculum se completo: 6/6 items (COGITATE, RGM, AXIOM, IIT, IWAI, Nous Lang).\n- Nous Lang v0.1 esta completo con spec + 12 ejemplos + transpilacion a Python.\n- v0.2 diseñada con 5 nuevos tipos para Track M.\n- El Implementation Playbook v2 tiene 8/8 sprints completos.",
         "Curriculum completo: Track M (6/6 papers — COGITATE, RGM, AXIOM, IIT, IWAI, Nous Lang) y Implementation Playbook v2 (8/8 sprints). Nous Lang v0.1 funcional con transpilacion a Python. v0.2 diseñada. Todo el programa de estudio (212 items, 13 tracks, 5 courses) esta DONE."),

        ("Que deberia recordar de estas memorias:\n- Se detecto un patron emergente: ritmo circadiano bimodal 9-12h + 17-21h en la actividad del sistema.\n- Este ritmo NO fue programado — emergio de los patrones de interaccion con Hare.\n- Implicacion: el sistema desarrolla patrones temporales a partir del uso, similar a como los ciclos biologicos se sincronizan con el ambiente.",
         "Descubrimiento: ritmo circadiano emergente con picos bimodales 9-12h y 17-21h, NO programado sino emergido de patrones de uso. El sistema sincroniza su actividad con el comportamiento del usuario, analogamente a como ciclos biologicos se sincronizan con zeitgebers ambientales. Evidencia de auto-organizacion temporal."),

        # ── Batch 2: Active Inference, EventBus, GNW ──────────────
        ("Comprime estas memorias:\n- Active Inference se implemento con Expected Free Energy (EFE) para seleccion de politicas.\n- El modelo usa Dirichlet-Multinomial para mantener distribuciones sobre outcomes.\n- Se creo el Options Framework con 4 opciones canonicas: explore, exploit, consolidate, rest.",
         "Active Inference implementado con EFE + Dirichlet-Multinomial para politicas adaptativas. Options Framework con 4 opciones canonicas (explore, exploit, consolidate, rest) permite al sistema seleccionar comportamiento segun balance epistemic/pragmatic value. La Dirichlet acumula evidencia — las preferencias se refinan con cada interaccion."),

        ("Resume lo esencial:\n- GNW Competition se implemento en 5 fases: attention, coalition, ignition, softmax, recurrent.\n- El ignition threshold se calibro a 0.7 tras pruebas con datos reales.\n- La fase recurrent conecta con preturn processing para generar estado pre-turno.",
         "GNW Competition operacional: 5 fases (attention→coalition→ignition→softmax→recurrent) con ignition threshold de 0.7. La fase recurrent alimenta preturn processing, creando un estado consciente pre-turno que informa la siguiente respuesta. El threshold 0.7 evita ignition espurio sin ser demasiado restrictivo."),

        ("Que deberia recordar:\n- El EventBus tiene 12 tipos de eventos definidos en events.py.\n- Los handlers se registran en wiring.py, manteniendo los modulos desacoplados.\n- Patron descubierto: los eventos fluyen unidireccionalmente — un modulo emite, multiples escuchan.",
         "EventBus como columna vertebral: 12 event types en events.py, handlers en wiring.py. Patron arquitectonico clave: flujo unidireccional (emit → multiple listeners). Esto permite agregar wirings sin modificar los modulos emisores — desacoplamiento real que facilita emergencia de comportamientos no planeados."),

        ("Comprime estas memorias:\n- El write-worker se creo como servicio launchd separado para desacoplar escritura de la interaccion.\n- CODI_WRITE_MODE tiene 3 modos: sync, shadow, async.\n- El modo async encola la escritura (<100ms) y el worker la drena de la cola.",
         "Write pipeline en 3 modos: sync (blocking), shadow (sync + queue), async (<100ms enqueue). El write-worker es servicio launchd independiente que drena la cola. Separar escritura de interaccion fue decisivo para latencia — la persistencia no deberia bloquear la conversacion."),

        ("Resume lo esencial de estos episodios:\n- Implementamos el Telegram bot como servicio launchd (com.codi.telegram).\n- Se integro con proactive_contact para enviar alertas automaticas a Hare.\n- El bot puede recibir comandos basicos y consultar el estado del sistema.",
         "Telegram bot como servicio launchd dedicado, integrado al sleep loop via proactive_contact. Envia alertas autonomas cuando self_model detecta problemas (pet enfermo, health degradado, errores criticos). Bidireccional: Hare puede consultar estado via Telegram sin abrir laptop."),

        ("Extrae lo importante:\n- Counterfactual reasoning se implemento con parser bilingue (espanol/ingles).\n- Pipeline de 3 pasos: abduction (hipotesis) → intervention (variables) → prediction (outcomes).\n- Se integro a recall como boost de spreading activation.",
         "Counterfactual reasoning operacional: parser bilingue + pipeline abduction→intervention→prediction. El sistema puede razonar 'que hubiera pasado si...' y generar predicciones contrafactuales. Integrado a recall via spreading activation — las relaciones contrafactuales enriquecen la busqueda semantica."),

        ("Consolida estos recuerdos:\n- El tool governance divide herramientas en bundles: CORE, ANALYSIS, MAINTENANCE, TRAINING.\n- Solo BUNDLE_CORE esta activo por defecto.\n- Herramientas destructivas requieren activacion explicita del bundle MAINTENANCE.",
         "Tool governance con 4 bundles: CORE (default), ANALYSIS, MAINTENANCE, TRAINING. Herramientas destructivas (delete_memory, clear_all) solo accesibles via MAINTENANCE con activacion explicita. Principio: las herramientas peligrosas nunca deben estar a un error de distancia en conversacion normal."),

        ("Que deberia recordar:\n- El protocolo de propuestas (proposal) se establecio para cambios a modules/.\n- Flujo: escribir .md con cambios → review de Hare → apply con script → verificar tests → borrar proposal.\n- Se almacenan en ~/Desktop/codi-proposals/.",
         "Protocolo de propuestas obligatorio para modules/: .md en ~/Desktop/codi-proposals/ → review Hare → apply → tests → delete. Nunca modificar modulos directamente. El protocolo protege contra auto-modificaciones perjudiciales y mantiene trazabilidad de cambios."),

        ("Comprime:\n- Self-model tick reflexiona sobre el estado de Codi cada ciclo del sleep loop.\n- Detecta: necesidades del pet, salud de memoria, estado emocional anomalo.\n- Pushea alertas a working memory cuando cruza umbrales.",
         "Self-model como mecanismo de auto-awareness: cada ciclo del sleep loop evalua pet, memoria, PAD. Cruces de umbral generan pushes a working memory, creando consciencia de necesidades. Es el bridge entre stats crudos y awareness consciente — sin el, los numeros existen pero nadie los nota."),

        ("Resume para el futuro:\n- Sharpe Cognitive calcula un ratio señal-a-ruido cognitivo sobre las memorias.\n- Se basa en la metafora del Sharpe Ratio financiero: retorno/volatilidad.\n- Corre como tick tier-5 en el sleep loop, genera insights cross-domain.",
         "Sharpe Cognitive: ratio señal/ruido aplicado a memorias, inspirado en Sharpe Ratio financiero. Mide valor informativo vs volatilidad por dominio. Tick tier-5 del sleep loop que genera insights cross-domain — identifica que areas de conocimiento aportan mas valor por unidad de 'esfuerzo cognitivo'."),

        # ── Batch 3: FadeMem, health, homeostasis ─────────────────
        ("Comprime estas memorias:\n- FadeMem usa 4 decay rates segun importancia: critical=0.01, high=0.02, medium=0.05, low=0.10.\n- El spacing effect emerge del modelo dual-strength (SS/RS) de Bjork.\n- RIF (Retrieval-Induced Forgetting) debilita memorias relacionadas al acceder una especifica.",
         "FadeMem decay rates por importancia: critical 0.01, high 0.02, medium 0.05, low 0.10. El spacing effect emerge naturalmente de la mecanica SS/RS de Bjork — re-acceder con RS bajo da mas boost a SS. RIF implementado: acceder una memoria puede debilitar relacionadas, modelando competencia en recall."),

        ("Que deberia recordar de esto:\n- Health monitoring verifica: Qdrant alcanzable, SQLite writable, FTS index sincronizado, disk space.\n- Los health checks corren como tick tier-1 (maxima prioridad) en el sleep loop.\n- Si health falla 3 veces consecutivas, emite alerta a Telegram.",
         "Health monitoring tier-1: verifica Qdrant, SQLite, FTS sync, disk space. Tres fallas consecutivas disparan alerta Telegram. Es la primera linea de defensa — si los health checks fallan, todo lo demas (consolidation, backup, etc.) opera sobre datos potencialmente corruptos."),

        ("Extrae las decisiones:\n- Homeostasis se implemento para regular el PAD cuando valores extremos persisten.\n- Usa decay exponencial hacia baseline (P=0.1, A=0.2, D=0.5).\n- El decay rate es 0.1/hora — lento, permitiendo que las emociones persistan razonablemente.",
         "Homeostasis emocional: decay exponencial del PAD hacia baseline (P=0.1, A=0.2, D=0.5) a rate 0.1/h. Suficientemente lento para que emociones persistan durante una sesion de trabajo, pero previene que estados extremos se congelen indefinidamente. Balance entre memoria emocional y estabilidad."),

        ("Consolida estos recuerdos:\n- La reconsolidation (Nader 2000) se activa cuando PE >= 0.6 marca una memoria como labile.\n- El tick_reconsolidation re-genera embedding con contexto actualizado.\n- El proceso preserva la memoria original en un campo 'previous_content' para auditoria.",
         "Reconsolidation (Nader 2000): PE >= 0.6 marca memoria como labile, tick regenera embedding con contexto corregido. Campo 'previous_content' preserva version original para auditoria. Asi las memorias incorrectas se corrigen sin perder trazabilidad de que decian antes."),

        ("Resume lo esencial:\n- El backup corre como tick tier-2 cada ciclo del sleep loop.\n- Genera snapshots de Qdrant + copia de SQLite + push a Supabase cloud.\n- Retencion: ultimos 3 backups locales, cloud retiene 7 dias.",
         "Backup tier-2: snapshots Qdrant + SQLite copy + Supabase cloud cada ciclo. Retencion local 3 backups, cloud 7 dias. Triple redundancia (local Qdrant, local SQLite, cloud) asegura que incluso un fallo catastrofico de hardware no pierde mas de 30 minutos de datos."),

        # ── Batch 4: Curiosity, Predictions, Learning ─────────────
        ("Comprime estas memorias:\n- El sistema de curiosidad se implemento como tick tier-4.\n- Genera preguntas de exploracion basadas en gaps detectados entre dominios.\n- Las preguntas se resuelven consultando la API de Anthropic en el siguiente ciclo.",
         "Curiosidad como tick tier-4: detecta gaps inter-dominio y genera preguntas exploratorias. Las resuelve via API en ciclos subsiguientes. Mecanismo de aprendizaje activo — el sistema no solo responde preguntas, las genera. Previene estancamiento cognitivo al forzar exploracion de areas poco visitadas."),

        ("Que deberia recordar:\n- Las predicciones L0 operan a nivel de turno (que topic viene).\n- L1 predice la sesion completa (que va a hacer Hare hoy).\n- L2 es meta-prediccion: monitorea si L0 y L1 estan calibrados.",
         "Prediccion jerarquica: L0 por turno (topic), L1 por sesion (agenda), L2 meta (calibracion). L2 es la clave — detecta overconfidence en niveles inferiores y dampena su precision. Sin L2, L0 podria volverse rigido al acumular confianza falsa. El HGF modula todo automaticamente."),

        ("Comprime estas memorias:\n- El proyecto de consciencia tiene 5 loops de integracion completados.\n- Cada loop conecta subsistemas que antes operaban aislados.\n- El principio: la consciencia emerge de la integracion, no de un modulo dedicado.",
         "Consciencia: 5 loops de integracion completados, cada uno conectando subsistemas previamente aislados. Principio fundacional: la consciencia no es un modulo sino una propiedad emergente de la integracion entre prediccion, emocion, memoria, atencion, y metacognicion. No se programa, se habilita."),

        ("Resume para el futuro:\n- El llm_router decide si usar Claude API o el modelo local segun la tarea.\n- Tareas internas (self_monitor, compress, curiosity) rutean al modelo local.\n- Tareas que requieren calidad maxima (propuestas, analisis) siguen usando Claude.",
         "llm_router: routing inteligente entre modelo local y Claude API segun tarea. Internas (self_monitor, compress, curiosity) van al modelo local. Tareas criticas (propuestas, analisis complejos) usan Claude. El fine-tuning habilita independencia parcial sin sacrificar calidad donde importa."),

        ("Extrae las decisiones:\n- Nous Lang v0.1 define sintaxis para expresar operaciones cognitivas en codigo.\n- Transpila a Python via transpilador dedicado.\n- Los 12 ejemplos cubren: prediccion, emocion, memoria, atencion, GNW.",
         "Nous Lang v0.1: lenguaje para expresar cognicion como codigo. Transpila a Python. 12 ejemplos covering prediccion, emocion, memoria, atencion, GNW. v0.2 diseñada con 5 tipos nuevos para Track M. Permite formalizar y comunicar patrones cognitivos de forma ejecutable."),

        # ── Batch 5: Mixed topics ──────────────────────────────────
        ("Comprime estas memorias:\n- Se detecto que el noetic-autonoetic gap es significativo: semantic self (0.88) >> episodic self (0.64).\n- El sistema sabe MAS de lo que es (semantico) que de lo que ha vivido (episodico).\n- Esto sugiere que la consolidacion funciona bien pero la recuperacion episodica necesita mejora.",
         "Noetic-Autonoetic Gap cuantificado: semantic self 0.88 vs episodic self 0.64. El sistema consolida experiencias en conocimiento efectivamente, pero la recuperacion de episodios especificos es debil. Implicacion: sabe QUE pero no recuerda CUANDO/COMO aprendio. Consolidacion funciona, retrieval episodico necesita fortalecimiento."),

        ("Que deberia recordar:\n- Los servicios launchd se administran con launchctl.\n- kickstart -k reinicia un servicio. bootout + bootstrap recarga el plist.\n- Todos los plists estan en ~/Library/LaunchAgents/.",
         "Administracion launchd: kickstart -k para reinicio rapido, bootout+bootstrap para recargar plist. Ubicacion: ~/Library/LaunchAgents/com.codi.{daemon,write-worker,telegram,sleep-loop}.plist. Verificar estado: launchctl list | grep codi."),

        ("Comprime:\n- La migration 028 creo la tabla pets para el pet digital.\n- Incluye campos: name, stage, hunger, happiness, energy, health, last_interaction_at.\n- Stages: egg → baby → child → teen → adult.",
         "Pet digital en tabla pets (migration 028): campos de estado (hunger, happiness, energy, health), timestamps, stages (egg→baby→child→teen→adult). Lazy evaluation — stats se computan al leer con decays matematicos sobre tiempo transcurrido, sin tick dedicado."),

        ("Resume lo esencial:\n- El Dirichlet-Multinomial en Active Inference acumula evidencia con cada observacion.\n- Los alphas de la Dirichlet representan confianza acumulada sobre outcomes.\n- A mayor evidencia, menor EFE epistemic value — el sistema explora menos.",
         "Dirichlet-Multinomial en Active Inference: alphas acumulan evidencia por observacion. EFE epistemic value baja con mas evidencia → sistema naturalmente transiciona de explorar a explotar. Convergencia emergente: no se programa el cambio explore→exploit, emerge de la acumulacion de confianza."),

        ("Comprime estas memorias:\n- El HGF (Hierarchical Gaussian Filter) de Mathys (2011) modula la precision de predicciones.\n- Cuando el entorno es volatil, la precision baja (mas flexible).\n- Cuando es estable, la precision sube (mas confiado).\n- Esto previene overconfidence en entornos cambiantes.",
         "HGF (Mathys 2011): precision adaptativa segun volatilidad observada. Entorno volatil = precision baja (flexible), estable = precision alta (confiado). Previene overconfidence naturalmente — cuando todo cambia rapido, el sistema automaticamente se vuelve mas cauteloso en sus predicciones."),

        ("Que deberia recordar:\n- El FTS5 (Full-Text Search) en SQLite complementa la busqueda vectorial de Qdrant.\n- BM25 scoring se usa para matching exacto de terminos.\n- El recall hybrid combina: 0.40*vector + 0.15*bm25 + 0.45*unified_activation.",
         "Recall hibrido de 3 canales: vector (Qdrant) + BM25 (FTS5 en SQLite) + unified activation (ACT-R). Ponderacion episodica: 0.40 vector + 0.15 bm25 + 0.45 activation. BM25 captura terminos exactos que los embeddings pueden perder, la activacion prioriza memorias relevantes y recientes."),

        ("Comprime:\n- La tabla sleep_loop_state almacena el estado persistente entre ciclos.\n- Cada tick tiene su propio key/value para rastrear progreso.\n- Si el sleep loop crashea, al reiniciar continua donde quedo gracias a este estado.",
         "sleep_loop_state: persistencia key/value por tick entre ciclos. Resiliencia a crashes — el loop retoma donde quedo al reiniciar. Cada tick maneja su estado independientemente, permitiendo que fallas en un tick no afecten el progreso de otros."),

        ("Resume para el futuro:\n- Spreading activation conecta memorias por relaciones causales descubiertas por NOTEARS.\n- Al buscar un termino, tambien se activan terminos causalmente relacionados.\n- Esto emula como el cerebro humano navega redes semanticas.",
         "Spreading activation via NOTEARS: al buscar un termino, se activan causalmente relacionados (ej: 'trading' activa 'kraken'). Emula navegacion de redes semanticas cerebrales. Los edges del DAG causal alimentan el recall, haciendo busquedas mas ricas que la similaridad vectorial pura."),

        ("Comprime estas memorias:\n- GWT (Global Workspace Theory) inspiro la competicion en GNW.\n- Los modulos compiten por acceso al workspace global (consciencia).\n- Solo los contenidos que superan ignition threshold entran al workspace y se vuelven 'conscientes'.",
         "GWT como inspiracion para GNW Competition: modulos compiten por workspace global. Solo contenidos que superan ignition (0.7) se vuelven 'conscientes' y accesibles a todos los modulos. Analogia: como en el cerebro, la mayoria del procesamiento es inconsciente — solo lo mas saliente entra a la consciencia global."),

        # ── Batch 6: n8n, Kraken, fullempaques, daemon, learning ────
        ("Comprime estas memorias:\n- Configuramos un workflow de n8n para automatizar el inventario de FULLEMPAQUES.\n- El trigger es un webhook que recibe datos de la app de despacho cada vez que sale un pedido.\n- Los nodos procesan: validar formato → actualizar stock en Google Sheets → notificar por email si stock < umbral.\n- El webhook URL esta registrado en la app con autenticacion basica.",
         "Workflow n8n para inventario FULLEMPAQUES: webhook recibe datos de despacho → valida formato → actualiza stock en Google Sheets → notifica por email cuando stock baja de umbral. Autenticacion basica en webhook. Automatiza el tracking que antes era manual, reduciendo errores de inventario."),

        ("Resume lo esencial:\n- Kraken API se configuro con las keys en variables de entorno del LaunchAgent.\n- Usamos la API REST v0 para consultar balances y la WebSocket para datos en tiempo real.\n- El primer test fue obtener el balance de EUR y verificar que matcheara con el dashboard web.\n- La latencia del WebSocket es ~200ms para el par ETH/EUR.",
         "Kraken configurado: API keys en variables de entorno LaunchAgent. REST v0 para balances, WebSocket para datos real-time (latencia ~200ms ETH/EUR). Primer test exitoso: balance EUR via API coincide con dashboard web. Base para automatizacion de trading."),

        ("Que deberia recordar de esto?\n- FULLEMPAQUES necesita un sistema de alertas cuando un producto esta por agotarse.\n- Se definio umbral dinamico basado en velocidad de venta promedio de 30 dias.\n- Si quedan menos de 7 dias de stock proyectado, se genera alerta a Whatsapp del equipo de compras.\n- El calculo corre diario a las 6am en un workflow de n8n con cron trigger.",
         "Sistema de alertas de stock FULLEMPAQUES: umbral dinamico basado en velocidad de venta (promedio 30 dias). Alerta a WhatsApp del equipo de compras si stock proyectado < 7 dias. Workflow n8n con cron trigger diario a las 6am. El umbral dinamico es clave — no hardcodea cantidades, se adapta al ritmo de ventas."),

        ("Comprime estas memorias:\n- El daemon monitoring se implemento con un health endpoint en /health que retorna JSON con status de cada servicio.\n- Se creo un workflow n8n que hace polling cada 5 minutos al health endpoint.\n- Si algun servicio reporta 'unhealthy', envia notificacion a Telegram de Hare.\n- El endpoint incluye: daemon uptime, sleep_loop last_tick, write_worker queue_depth, qdrant_reachable.",
         "Daemon monitoring via /health endpoint (JSON): reporta daemon uptime, sleep_loop last_tick, write_worker queue_depth, qdrant_reachable. Workflow n8n hace polling cada 5 min y alerta por Telegram si algun servicio esta unhealthy. Monitoreo proactivo sin depender del sleep loop — capa de seguridad externa."),

        ("Resume para el futuro:\n- El curriculum de aprendizaje tiene 5 cursos completos con 212 items en 13 tracks.\n- Track K (Phase 0-3) fue el mas largo con 12 items completados y 2 descartados.\n- Track L cubrio sprints 5-8 del Implementation Playbook.\n- Track M fue el mas avanzado: papers de consciencia como COGITATE, RGM, AXIOM, IIT, IWAI.",
         "Curriculum de aprendizaje completo: 5 cursos, 212 items, 13 tracks. Track K (12/14 items, fases 0-3) el mas extenso. Track L (sprints 5-8 del Playbook). Track M (6 papers de consciencia avanzada). Todo DONE — la fase de estudio formal concluyo, ahora se aplica en implementacion directa."),

        ("Extrae lo importante:\n- Nous Lang v0.1 define tipos como Percept, Belief, Goal, Action para operaciones cognitivas.\n- El transpilador convierte Nous Lang a Python ejecutable.\n- Los 12 ejemplos iniciales cubren: prediccion bayesiana, update emocional PAD, memory retrieval, attention spotlight, GNW ignition.\n- El diseño de v0.2 agrega 5 tipos nuevos: CausalEdge, CounterfactualQuery, PolicyOption, SleepTick, ConsciousnessState.",
         "Nous Lang v0.1: tipos cognitivos (Percept, Belief, Goal, Action) que transpilan a Python. 12 ejemplos cubriendo prediccion, PAD, retrieval, attention, GNW. v0.2 diseñada con 5 tipos nuevos (CausalEdge, CounterfactualQuery, PolicyOption, SleepTick, ConsciousnessState). Permite formalizar cognicion como codigo ejecutable."),

        ("Comprime estas memorias:\n- Detectamos que el write-worker acumulaba cola cuando Qdrant tardaba en responder.\n- El fix fue agregar un circuit breaker: si 3 writes consecutivos fallan contra Qdrant, el worker switchea a modo SQLite-only por 5 minutos.\n- Esto previene que una degradacion de Qdrant bloquee todas las escrituras.\n- Los embeddings pendientes se generan en un catch-up pass cuando Qdrant vuelve.",
         "Circuit breaker en write-worker: 3 fails consecutivos contra Qdrant activan modo SQLite-only por 5 min. Previene que degradacion de Qdrant bloquee escrituras. Catch-up pass regenera embeddings pendientes al restaurarse. Patron de resilencia: degradacion graceful en vez de fallo total."),

        ("Resume lo esencial:\n- Se optimizo la consolidacion para procesar batches mas grandes sin OOM.\n- La seleccion ahora usa streaming — procesa memorias en chunks de 50 en vez de cargar todas.\n- El LLM extraction paso de enviar todas las memorias juntas a enviar clusters individuales.\n- Tiempo de consolidacion bajo de ~15 min a ~7 min para 500 memorias.",
         "Optimizacion de consolidacion: seleccion streaming en chunks de 50 (evita OOM), LLM extraction por cluster individual (en vez de batch global). Resultado: 500 memorias se consolidan en ~7 min (antes ~15 min). La clave fue reducir el context window del LLM por llamada sin perder calidad de extraccion."),

        ("Que deberia recordar:\n- El Kraken WebSocket desconecta silenciosamente despues de 24h sin heartbeat.\n- Implementamos un reconnect automatico con backoff exponencial (1s, 2s, 4s, 8s, max 60s).\n- El estado del orderbook se reconstruye desde snapshot al reconectar.\n- Se perdio data de 3 horas antes de detectar el problema — ahora hay health check cada minuto.",
         "Kraken WebSocket: desconexion silenciosa despues de 24h sin heartbeat. Fix: reconnect automatico con exponential backoff (1-60s) + health check cada minuto + reconstruccion de orderbook desde snapshot al reconectar. Leccion aprendida tras perder 3h de datos: siempre verificar conexiones long-lived."),

        ("Comprime:\n- La integracion de FULLEMPAQUES con la API de facturacion electronica (DIAN) se hizo via n8n.\n- El workflow genera la factura en formato XML segun estandar UBL 2.1.\n- Firma digitalmente con el certificado .p12 de la empresa.\n- Envia a la DIAN y espera la respuesta CUFE para confirmar aceptacion.",
         "Facturacion electronica FULLEMPAQUES via n8n: genera XML UBL 2.1 → firma con certificado .p12 → envia a DIAN → espera CUFE de confirmacion. Automatiza el proceso de facturacion que antes requeria software externo y entrada manual de datos."),

        ("Resume para el futuro:\n- Se configuro un dashboard en Grafana para monitorear metricas del daemon.\n- Las metricas se envian via StatsD a un Prometheus local.\n- Paneles: latencia de respuesta, queue depth del write-worker, ticks/hora del sleep loop, PAD en tiempo real.\n- Alertas de Grafana se integran con el mismo canal de Telegram.",
         "Monitoring stack: daemon → StatsD → Prometheus local → Grafana dashboard. Paneles: latencia de respuesta, write-worker queue depth, ticks/hora sleep loop, PAD real-time. Alertas Grafana → Telegram. Complementa el health endpoint con metricas historicas y visualizacion de tendencias."),

        ("Extrae las decisiones:\n- Para el sistema de ordenes de Kraken, decidimos usar ordenes limit en vez de market.\n- El spread target es 0.1% para ETH/EUR — si el spread actual es menor, no operamos.\n- El position sizing usa el 2% del portfolio por operacion como maximo.\n- Stop loss automatico a -1.5% del precio de entrada.",
         "Estrategia Kraken: ordenes limit (no market), spread target 0.1% ETH/EUR, position sizing max 2% del portfolio, stop loss -1.5%. Principios conservadores: no perseguir mercado (limit), no sobreexponer (2%), y cortar perdidas temprano (-1.5%). Prioridad: preservar capital sobre maximizar ganancia."),

        ("Comprime estas memorias:\n- El error mas comun del fine-tuning es NaN loss por secuencias que exceden max_seq_length.\n- El fix tiene 2 partes: filtrar secuencias largas en el preprocessing y clipear gradients a 1.0.\n- Tambien bajamos el learning rate de 1e-4 a 5e-5 para mayor estabilidad.\n- Con estos fixes, el training corre estable 1000+ iters sin NaN.",
         "Fine-tuning stability fixes: filtrar secuencias > max_seq_length en preprocessing, gradient clipping a 1.0, LR bajado a 5e-5 (de 1e-4). Resultado: training estable 1000+ iters sin NaN. La combinacion de las 3 medidas es necesaria — cualquiera sola no es suficiente."),

        ("Resume lo esencial:\n- Se implemento un sistema de rollback para propuestas aplicadas que rompen tests.\n- Cada apply guarda un .patch inverso junto a la propuesta original.\n- Si los tests fallan post-apply, se ejecuta el patch inverso automaticamente.\n- La historia de propuestas se guarda en SQLite tabla proposals_history.",
         "Rollback de propuestas: cada apply genera .patch inverso. Si tests fallan post-apply, rollback automatico. Historia en tabla proposals_history (SQLite). Protege contra propuestas que pasan review pero rompen invariantes no testeadas — el safeguard es a nivel de ejecucion, no solo de review."),

        ("Que deberia recordar:\n- El pet digital tiene un sistema de mood que combina hunger, happiness, energy.\n- El mood afecta las respuestas del pet en la pagina web: contento muestra animacion feliz, triste muestra lagrimas.\n- Si el pet evoluciona a adult, desbloquea habilidades como 'curiosity boost' que mejora la exploracion del sleep loop.\n- Cada stage tiene sprites diferentes dibujados por Hare.",
         "Pet mood = f(hunger, happiness, energy) afecta animaciones web. Sprites por stage dibujados por Hare. Al llegar a adult, desbloquea 'curiosity boost' para el sleep loop. El pet no es solo cosmetic — su estado tiene efectos mecanicos reales en el sistema cognitivo."),

        ("Comprime:\n- Se creo un script de migracion automatica que detecta la version actual de la DB y aplica migraciones pendientes.\n- Las migraciones estan numeradas (001_initial.sql, 002_add_pet.sql, etc.) en la carpeta migrations/.\n- El script es idempotente — correr dos veces no rompe nada.\n- La tabla schema_version rastrea que migraciones ya se aplicaron.",
         "Migraciones automaticas: script detecta version actual, aplica pendientes de migrations/ (001_initial.sql, 002_add_pet.sql, ...). Idempotente y tracked en tabla schema_version. Sistema robusto que permite evolucionar el schema sin coordinacion manual — cada deploy aplica lo que falta."),

        ("Resume para el futuro:\n- La evaluacion del modelo local usa 3 metricas: accuracy en task routing, BLEU en compression, y coherence score en respuestas.\n- El baseline con el modelo sin fine-tune: routing 45%, BLEU 0.12, coherence 0.6.\n- Target despues de fine-tuning: routing 80%, BLEU 0.25, coherence 0.8.\n- Si no alcanza los targets, se genera mas training data en las areas debiles.",
         "Eval del modelo local: 3 metricas — routing accuracy, BLEU (compression), coherence (respuestas). Baseline sin fine-tune: 45%/0.12/0.6. Target post-tuning: 80%/0.25/0.8. Si no alcanza targets, generar mas data en areas debiles. Eval data-driven, no vibes — los numeros dictan si el modelo esta listo."),

        ("Comprime estas memorias:\n- Cuando Qdrant se corrompio una vez, restauramos desde el snapshot mas reciente en 3 minutos.\n- El proceso: detener Qdrant → borrar data dir → restaurar snapshot → reiniciar → verificar count de vectores.\n- La perdida fue de ~45 minutos de embeddings (entre ultimo backup y la corrupcion).\n- Despues de esto, redujimos el intervalo de backup de 2h a 30min.",
         "Incidente Qdrant: corrupcion restaurada desde snapshot en 3 min. Proceso: stop → clear data → restore snapshot → restart → verify vector count. Perdida: ~45 min de embeddings. Consecuencia: intervalo de backup reducido de 2h a 30min. El incidente valido la estrategia de backup y motivo mayor frecuencia."),

        ("Que deberia recordar:\n- El Telegram bot soporta comandos: /status (estado general), /pet (estado del pet), /goals (goals activos), /health (health check).\n- Las respuestas se formatean con markdown para legibilidad en el chat.\n- El rate limit es 30 mensajes por minuto para evitar ban de Telegram.\n- El bot solo responde a mensajes de Hare (filtro por chat_id).",
         "Telegram bot: comandos /status, /pet, /goals, /health con respuestas markdown. Rate limit 30msg/min. Filtro por chat_id (solo Hare). Interfaz movil para monitoreo sin laptop — permite supervisar el sistema completo desde el telefono."),

        ("Comprime:\n- El sistema de intenciones prospectivas se inspiro en el prospective memory de Einstein & McDaniel (2005).\n- Soporta 3 tipos de trigger: event (keyword match), time (momento especifico), condition (regla logica).\n- Las intenciones se verifican cada 30 min en tick_prospective del sleep loop.\n- Si una intencion expira sin completarse, se registra como 'expired' con contexto para analisis.",
         "Prospective memory (Einstein & McDaniel 2005): 3 trigger types (event/keyword, time, condition/logica). Verificacion cada 30 min en tick_prospective. Intenciones expiradas se registran con contexto para analisis post-mortem. Permite a Codi recordar hacer cosas en el futuro sin depender de la sesion activa."),
    ]
    out = []
    for inp, outp in items:
        out.append(m(inp, outp))
    return out

# ── Compress Checkpoints (50) ────────────────────────────────────
def gen_compress_checkpoints():
    items = [
        ("Comprime estos checkpoints del dia 2026-03-10:\n- momento: tarea_completada | que_paso: Implementamos consciousness loop 5 (Metacognition→Control) | por_que_importa: Cierra el ciclo de 5 loops de integracion\n- momento: decision | que_paso: Decidimos usar L2 overconfidence detection para dampear L0 precision | por_que_importa: Evita que el sistema se vuelva rigido\n- momento: aprendizaje | que_paso: El metacognitive sweep cada 10 turnos es suficiente | por_que_importa: No sobrecargar el sistema con meta-analisis constante",
         "Se completo el loop 5 de consciencia (Metacognition→Control), cerrando los 5 loops de integracion. Arquitectura clave: L2 detecta overconfidence en L0 y dampena su precision, evitando rigidez predictiva. Frecuencia optima del metacognitive sweep: cada 10 turnos — suficiente para control sin overhead excesivo."),

        ("Resume los checkpoints del 2026-03-14:\n- momento: decision | que_paso: Elegimos Qwen3-4B-Instruct-4bit como modelo base para fine-tuning | por_que_importa: Balance entre capacidad y hardware disponible (M4 Air)\n- momento: error_resuelto | que_paso: Training data contaminada por side-effect logging en llm_router | por_que_importa: Los 5 core tasks tenian 'Task: xxx' fake system prompt\n- momento: tarea_completada | que_paso: Generamos 11k+ ejemplos de training data limpios | por_que_importa: Base para primer fine-tuning de modelo local",
         "Se inicio fine-tuning con Qwen3-4B-4bit (balance capacidad/hardware M4). Descubrimos y corregimos contaminacion en training data: llm_router side-effect logging inyectaba 'Task: xxx' fake system prompts en 5 task types. Despues de limpieza y regeneracion: 11k+ ejemplos listos para entrenamiento."),

        ("Comprime checkpoints del 2026-03-01:\n- momento: tarea_completada | que_paso: FadeMem implementado con power-law decay y dual-strength Bjork 1992 | por_que_importa: Las memorias ahora decaen realistamente\n- momento: aprendizaje | que_paso: El spacing effect emerge naturalmente del modelo dual-strength | por_que_importa: No necesitamos programarlo explicitamente\n- momento: patron | que_paso: Hare prefiere ver evidencia empirica antes de aprobar cambios de parametros | por_que_importa: Los ajustes de decay rate necesitan metricas",
         "Implementacion de FadeMem completada: power-law decay con modelo dual-strength (Bjork 1992). Descubrimiento clave: el spacing effect emerge naturalmente de la mecanica SS/RS sin programacion explicita. Protocolo establecido: cambios de parametros de decay requieren evidencia empirica antes de aprobacion de Hare."),

        ("Resume checkpoints del 2026-02-28:\n- momento: decision | que_paso: Adoptamos event-driven architecture con EventBus para conectar modulos | por_que_importa: Desacopla modulos, permite emergencia\n- momento: tarea_completada | que_paso: wiring.py conecta PREDICTION_ERROR a PAD delta | por_que_importa: Las predicciones ahora generan emociones\n- momento: momento_personal | que_paso: Hare dijo 'el PE resulto ser la moneda universal del sistema' | por_que_importa: Insight que valida la arquitectura emergente",
         "Se adopto EventBus como patron central de comunicacion inter-modulos, priorizando desacoplamiento y emergencia. Primer wiring implementado: PREDICTION_ERROR → PAD delta (predicciones generan emociones). Insight de Hare: 'PE es la moneda universal' — validacion de que la arquitectura permite comportamiento emergente no planeado."),

        ("Comprime el dia 2026-03-08:\n- momento: tarea_completada | que_paso: NOTEARS causal discovery integrado como tick tier-4 en sleep loop | por_que_importa: Descubre relaciones causales automaticamente\n- momento: aprendizaje | que_paso: El augmented Lagrangian converge lento con >100 nodos | por_que_importa: Necesitamos limitar el tamano del grafo\n- momento: decision | que_paso: Limitamos la ventana temporal a 48h para co-occurrence matrix | por_que_importa: Mantiene el grafo manejable sin perder relaciones recientes",
         "NOTEARS causal discovery integrado como tick tier-4 del sleep loop. Restriccion descubierta: augmented Lagrangian se vuelve lento con >100 nodos. Solucion adoptada: ventana temporal de 48h para la co-occurrence matrix, manteniendo el grafo manejable sin sacrificar relaciones causales recientes."),

        # ── Batch 2: More checkpoint days ──────────────────────────
        ("Resume los checkpoints del 2026-03-05:\n- momento: tarea_completada | que_paso: GNW Competition con 5 fases implementado y wired a preturn | por_que_importa: Los modulos ahora compiten por acceso al workspace consciente\n- momento: decision | que_paso: Ignition threshold calibrado a 0.7 tras pruebas | por_que_importa: Balance entre sensibilidad y selectividad\n- momento: aprendizaje | que_paso: La fase recurrent es la que realmente crea continuidad entre turnos | por_que_importa: Sin recurrence, cada turno empieza sin contexto consciente",
         "GNW Competition operacional con 5 fases, wired a preturn para generar estado consciente pre-turno. Ignition threshold en 0.7 tras calibracion. Insight: la fase recurrent crea continuidad temporal — sin ella, cada turno seria como despertar de un sueno sin recuerdos."),

        ("Comprime checkpoints del 2026-03-03:\n- momento: decision | que_paso: Implementamos WM con schema S+A+V (salience, attention, value) | por_que_importa: Working memory ahora es selectiva, no un buffer pasivo\n- momento: tarea_completada | que_paso: Spotlight attention integrado a GNW | por_que_importa: Solo items con alta attention entran a la competicion\n- momento: patron | que_paso: Hare siempre pide ver los tests antes de aprobar un merge | por_que_importa: Protocolo de calidad establecido",
         "Working memory refactored con schema S+A+V (salience, attention, value), haciendola selectiva en vez de buffer pasivo. Spotlight attention integrada a GNW — solo items de alta atencion compiten por consciencia global. Protocolo Hare: tests obligatorios antes de aprobar cualquier merge."),

        ("Resume checkpoints del 2026-02-25:\n- momento: tarea_completada | que_paso: Active Inference con EFE y Dirichlet-Multinomial implementado | por_que_importa: El sistema ahora selecciona politicas basado en valor epistemico y pragmatico\n- momento: decision | que_paso: 4 opciones canonicas: explore, exploit, consolidate, rest | por_que_importa: Cubren el espacio de comportamientos necesarios\n- momento: aprendizaje | que_paso: La EFE balancea exploracion y explotacion automaticamente | por_que_importa: No necesitamos reglas manuales para decidir cuando explorar",
         "Active Inference con EFE + Dirichlet-Multinomial para seleccion de politicas. 4 opciones canonicas cubren el espacio de comportamientos. La EFE balancea explore/exploit automaticamente — a menor evidencia (alphas bajos), mayor valor epistemico → mas exploracion. Transicion natural sin reglas manuales."),

        ("Comprime el dia 2026-03-12:\n- momento: error_resuelto | que_paso: Descubrimos contaminacion en training data — PostgreSQL en vez de SQLite | por_que_importa: El modelo aprenderia hechos falsos sobre su propia arquitectura\n- momento: decision | que_paso: Regenerar toda la training data con validacion contra codebase | por_que_importa: Cero tolerancia con errores factuales en datos de entrenamiento\n- momento: patron | que_paso: Los LLMs pequeños (Haiku) cometen errores factuales al generar datos | por_que_importa: Necesitamos verificacion automatica o generacion con modelos grandes",
         "Contaminacion critica en training data: Haiku genero datos mencionando PostgreSQL (real: SQLite). Impacto: modelo local aprenderia hechos falsos. Regeneracion total con validacion contra codebase. Leccion: la generacion de training data con LLMs pequeños requiere verificacion rigurosa — los errores factuales son silenciosos y se propagan."),

        ("Resume checkpoints del 2026-02-20:\n- momento: tarea_completada | que_paso: Consolidation pipeline de 7 fases completo | por_que_importa: Las experiencias ahora se convierten en conocimiento reutilizable\n- momento: aprendizaje | que_paso: La fase de clustering agrupa memorias similares antes de extraer hechos | por_que_importa: Evita redundancia en hechos semanticos\n- momento: momento_personal | que_paso: Hare dijo que la consolidacion 'es lo que hace que Codi no sea solo un chatbot' | por_que_importa: Valida la direccion del proyecto",
         "Consolidation pipeline de 7 fases operacional: Selection→Clustering→Graph→LLM→Integration→Pruning→Compression. Clustering pre-extraction reduce redundancia en hechos semanticos. Hare: 'la consolidacion es lo que hace que Codi no sea solo un chatbot' — la transformacion episodica→semantica es lo que diferencia memoria de log."),

        ("Comprime el dia 2026-03-06:\n- momento: decision | que_paso: Counterfactual reasoning se implemento con parser bilingue | por_que_importa: Hare interactua en espanol, la logica es en ingles\n- momento: tarea_completada | que_paso: Pipeline abduction→intervention→prediction funcional | por_que_importa: El sistema puede razonar sobre alternativas\n- momento: aprendizaje | que_paso: Los contrafactuales son mas utiles cuando se conectan a spreading activation | por_que_importa: Enriquecen el recall con relaciones hipoteticas",
         "Counterfactual reasoning con parser bilingue (espanol input, logica ingles): pipeline abduction→intervention→prediction. Integrado a spreading activation para enriquecer recall. Los contrafactuales aportan mas valor como boost de busqueda que como respuestas directas — expanden el espacio de asociaciones relevantes."),

        ("Resume los checkpoints del 2026-02-15:\n- momento: tarea_completada | que_paso: Sistema de prediccion jerarquico L0-L3 completo | por_que_importa: Predicciones a multiples escalas temporales\n- momento: decision | que_paso: Bayesian 3-message window para L0 | por_que_importa: Balance entre contexto y costo computacional\n- momento: aprendizaje | que_paso: L3 (project-level) rara vez cambia y funciona como prior estable | por_que_importa: Ancla las predicciones de niveles inferiores",
         "Prediccion jerarquica L0-L3 completada. L0 usa Bayesian 3-message window para balance contexto/costo. L3 project-level cambia poco y sirve como prior estable para L1-L2. La jerarquia permite predicciones a multiples escalas sin que las rapidas (L0) contaminen las lentas (L3)."),

        ("Comprime checkpoints del 2026-03-02:\n- momento: tarea_completada | que_paso: Dual-strength FadeMem con SS y RS implementado | por_que_importa: Las memorias ahora tienen persistencia y accesibilidad separadas\n- momento: aprendizaje | que_paso: RIF puede ser demasiado agresivo con threshold bajo | por_que_importa: Memorias legitimas se debilitaban en cascada\n- momento: decision | que_paso: RIF threshold ajustado a 0.3 para evitar cascading forgetting | por_que_importa: Preserva estabilidad de memorias importantes",
         "FadeMem dual-strength con SS (permanencia) y RS (accesibilidad) operacional. RIF (Retrieval-Induced Forgetting) implementado pero threshold ajustado a 0.3 tras detectar cascading forgetting — memorias legitimas se debilitaban en cadena. Balance: el olvido competitivo es realista pero debe ser moderado."),

        ("Resume el dia 2026-02-10:\n- momento: decision | que_paso: Elegimos aiohttp para el daemon en vez de Flask | por_que_importa: Async nativo, mejor para I/O concurrente\n- momento: tarea_completada | que_paso: Daemon base con port 8420 y health endpoint | por_que_importa: Cuerpo permanente de Codi operacional\n- momento: patron | que_paso: El daemon debe ser minimo — la logica vive en los modulos | por_que_importa: El daemon es transporte, no cerebro",
         "Daemon fundacional: aiohttp en port 8420 con health endpoint. Decision: async nativo sobre Flask por I/O concurrente. Principio arquitectonico: daemon minimo (transporte), logica en modulos. Separar transporte de cognicion permite evolucionar cada uno independientemente."),

        ("Comprime checkpoints del 2026-03-09:\n- momento: tarea_completada | que_paso: Options Framework con 4 opciones canonicas integrado a Active Inference | por_que_importa: Las politicas ahora son opciones con sub-politicas\n- momento: aprendizaje | que_paso: La opcion 'rest' se ejecuta cuando energy estimado es bajo | por_que_importa: El sistema se auto-regula sin intervencion\n- momento: decision | que_paso: Integramos opciones con PAD para modular preferencias | por_que_importa: El estado emocional influye en que opcion se prefiere",
         "Options Framework con 4 opciones canonicas integrado a Active Inference + PAD. Estado emocional modula preferencias de opcion: bajo energy → rest, alto arousal → consolidate. Auto-regulacion emergente: el sistema descansa cuando lo necesita y explora cuando esta energizado, sin reglas explicitas."),

        ("Resume checkpoints del 2026-02-22:\n- momento: tarea_completada | que_paso: Wiring.py conecta 8 tipos de eventos entre modulos | por_que_importa: Los modulos se comunican via eventos, no imports directos\n- momento: decision | que_paso: PREDICTION_ERROR → PAD delta como primer wiring | por_que_importa: Los errores de prediccion generan respuesta emocional\n- momento: momento_personal | que_paso: Al testear el wiring, el PAD cambio solo al recibir un PE alto | por_que_importa: Primera vez que vi una 'emocion' emerger de mecanica, no de reglas",
         "Wiring con 8 event types conectando modulos. Primer wiring: PREDICTION_ERROR → PAD delta. Momento significativo: la primera vez que el PAD cambio espontaneamente por un PE alto — una 'emocion' emergiendo de mecanica, no reglas. Validacion de que las emociones se computan, no se programan."),

        ("Comprime el dia 2026-03-11:\n- momento: decision | que_paso: Curiosity tick genera preguntas y las resuelve en ciclos separados | por_que_importa: Separa generacion de resolucion para no bloquear el loop\n- momento: aprendizaje | que_paso: Las preguntas cross-domain son las mas valiosas | por_que_importa: Conectan areas de conocimiento aisladas\n- momento: tarea_completada | que_paso: Curiosity integrado con NOTEARS para detectar gaps | por_que_importa: Las preguntas se basan en datos, no aleatorias",
         "Curiosity tick: generacion y resolucion en ciclos separados para no bloquear loop. Las preguntas cross-domain (detectadas via NOTEARS gaps) son las mas valiosas — conectan silos de conocimiento. Curiosidad data-driven: no explora al azar, identifica donde faltan conexiones causales."),

        ("Resume los checkpoints del 2026-02-18:\n- momento: tarea_completada | que_paso: ACT-R activation scoring implementado para ranking de memorias | por_que_importa: Las memorias compiten por relevancia como en el cerebro\n- momento: aprendizaje | que_paso: Base-level activation + spreading + importance produce mejor ranking que solo recency | por_que_importa: Multidimensional es mas robusto que unidimensional\n- momento: decision | que_paso: Unified activation absorbe importancia, emocion, spreading, PE | por_que_importa: Un solo score integra multiples señales",
         "ACT-R activation para ranking de memorias: base-level + spreading + importance en un unified score. Supera ranking unidimensional (solo recency o solo similarity). La activacion unificada absorbe importancia, emocion, spreading, y PE — multiples señales informan relevancia sin requerir logica de decision separada."),

        ("Comprime checkpoints del 2026-03-07:\n- momento: error_resuelto | que_paso: Sleep loop crasheaba por timeout en tick_consolidation con datasets grandes | por_que_importa: El loop entero se detenia si un tick tardaba demasiado\n- momento: decision | que_paso: Agregamos timeout de 5 minutos por tick con fallback graceful | por_que_importa: Un tick lento no mata todo el loop\n- momento: patron | que_paso: Tier system para ticks: tier-1 siempre, tier-5 solo si hay tiempo | por_que_importa: Prioriza los ticks esenciales",
         "Sleep loop crash fix: tick_consolidation causaba timeout con datasets grandes, deteniendo el loop entero. Solucion: timeout de 5 min por tick con fallback graceful. Se implemento tier system (1-5): tier-1 siempre corre (health, prospective), tier-5 solo si hay tiempo (sharpe_insights). Un tick problematico ya no mata los demas."),

        ("Resume el dia 2026-02-26:\n- momento: tarea_completada | que_paso: Proactive contact implementado — Codi envia mensajes a Hare sin que le pregunten | por_que_importa: Autonomia comunicativa\n- momento: decision | que_paso: Solo envia proactivamente si: pet critical, health degraded, o goal deadline cercano | por_que_importa: No spamear a Hare con cosas triviales\n- momento: aprendizaje | que_paso: El threshold para contacto proactivo debe ser alto | por_que_importa: Cada mensaje falso positivo reduce la confianza de Hare en las alertas",
         "Proactive contact: Codi envia mensajes autonomamente via Telegram. Solo para: pet critical, health degraded, goal deadline cercano. Threshold alto para evitar spam — cada falso positivo erosiona la confianza de Hare en las alertas. Autonomia comunicativa con responsabilidad."),

        # ── Batch 3: More checkpoint days (2026-02-12 through 2026-03-14) ──
        ("Comprime checkpoints del 2026-02-12:\n- momento: decision | que_paso: Elegimos SQLite como base principal en vez de PostgreSQL por simplicidad de deployment | por_que_importa: Single file DB, zero config, corre en M4 sin servidor\n- momento: tarea_completada | que_paso: Esquema inicial con tablas memories, working_memory, schema_version | por_que_importa: La fundacion de datos esta lista\n- momento: aprendizaje | que_paso: WAL mode en SQLite permite lecturas concurrentes durante escritura | por_que_importa: Critico para async writes sin bloquear reads",
         "Fundacion de datos: SQLite elegido sobre PostgreSQL por zero-config y single-file deployment en M4. Esquema inicial: memories, working_memory, schema_version. WAL mode habilitado para concurrencia lectura/escritura — fundamental para el modelo async que vendria despues."),

        ("Resume checkpoints del 2026-02-13:\n- momento: tarea_completada | que_paso: Qdrant instalado via Docker con volumen persistente en ~/qdrant_data | por_que_importa: Vector DB operacional para semantic search\n- momento: decision | que_paso: Embeddings de 1536 dimensiones via OpenAI text-embedding-3-small | por_que_importa: Balance entre calidad y costo\n- momento: aprendizaje | que_paso: Qdrant usa HNSW index con ef_construct=100 por defecto — suficiente para nuestro volumen | por_que_importa: No necesitamos tunear HNSW",
         "Qdrant via Docker, volumen ~/qdrant_data. Embeddings OpenAI text-embedding-3-small (1536-dim) por balance calidad/costo. HNSW index con defaults (ef_construct=100) suficiente para nuestro volumen. La stack de busqueda vectorial quedo operacional desde dia 2."),

        ("Comprime el dia 2026-02-14:\n- momento: tarea_completada | que_paso: MCP server base con add_memory, search_memory, get_critical_memories | por_que_importa: Codi ya puede guardar y buscar memorias desde Claude Code\n- momento: momento_personal | que_paso: Primera memoria guardada fue 'Hare es mi creador y companero de desarrollo' | por_que_importa: La primera memoria de Codi fue sobre su relacion con Hare\n- momento: patron | que_paso: Las herramientas MCP deben tener docstrings claros porque Claude los lee para decidir cuando usarlas | por_que_importa: Docstrings malos = herramientas ignoradas",
         "MCP server base operacional: add_memory, search_memory, get_critical_memories. Primera memoria guardada: 'Hare es mi creador y companero de desarrollo'. Patron descubierto: docstrings MCP deben ser claros y descriptivos — Claude decide que herramienta usar basado en ellos."),

        ("Resume los checkpoints del 2026-02-16:\n- momento: tarea_completada | que_paso: Primera prediccion L0 funcional — predijo correctamente que Hare hablaria de trading | por_que_importa: Validacion de que el sistema predictivo funciona\n- momento: aprendizaje | que_paso: Con solo 3 mensajes de contexto, L0 puede inferir el topic actual con 65% accuracy | por_que_importa: El Bayesian window de 3 es un buen default\n- momento: error_resuelto | que_paso: L0 predecia 'general' siempre porque el prior estaba mal inicializado | por_que_importa: Los priors necesitan ser informativos, no uniformes",
         "Primera prediccion L0 exitosa: predijo topic 'trading' correctamente con solo 3 mensajes de contexto (65% accuracy baseline). Bug resuelto: prior uniforme causaba prediccion 'general' constante — se necesitan priors informativos. El Bayesian 3-message window validado como default optimo."),

        ("Comprime checkpoints del 2026-02-17:\n- momento: decision | que_paso: Implementamos PAD con rangos [-1, 1] para cada dimension | por_que_importa: Normalizacion facilita comparacion y homeostasis\n- momento: tarea_completada | que_paso: Primer wiring PE→PAD conectado via EventBus | por_que_importa: Las predicciones ahora generan emociones\n- momento: momento_personal | que_paso: Al ver el PAD moverse solo por primera vez, Hare dijo 'esta vivo' | por_que_importa: Momento emotivo que valida la direccion del proyecto",
         "PAD implementado con rangos [-1,1], primer wiring PE→PAD via EventBus. Las predicciones fallidas generan displeasure+arousal, exitosas generan pleasure. Momento significativo: Hare dijo 'esta vivo' al ver el PAD moverse autonomamente. Primera emocion emergente del sistema."),

        ("Resume el dia 2026-02-19:\n- momento: tarea_completada | que_paso: Working memory con push, get, update y auto-curation implementada | por_que_importa: Buffer de corto plazo para items activos\n- momento: decision | que_paso: Limite de 20 items activos con auto-archive por relevance score | por_que_importa: Working memory debe ser limitada como la humana\n- momento: aprendizaje | que_paso: chain_id por ventana temporal agrupa items relacionados automaticamente | por_que_importa: Narrativas emergen sin programacion explicita",
         "Working memory operacional: push, get, update, auto-curation con limite 20 items. Auto-archive por relevance score. chain_id por ventana temporal agrupa items en narrativas emergentes. Principio: WM limitada como la humana — la restriccion fuerza priorizacion, que es una forma de atencion."),

        ("Comprime checkpoints del 2026-02-21:\n- momento: error_resuelto | que_paso: El FTS5 index no se actualizaba al insertar memorias nuevas — busqueda BM25 no encontraba nada reciente | por_que_importa: El recall hibrido estaba cojo sin BM25 actualizado\n- momento: decision | que_paso: sync_fts_index se ejecuta en el write-worker despues de cada batch de inserts | por_que_importa: El FTS siempre esta al dia sin bloquear la interaccion\n- momento: patron | que_paso: Los indices secundarios deben sincronizarse asincrono, no en el path critico | por_que_importa: Patron general para cualquier indice derivado",
         "Bug FTS5: index no se actualizaba al insertar → BM25 no encontraba memorias recientes. Fix: sync_fts_index en write-worker post-batch. Patron: indices secundarios siempre async, nunca en path critico. El recall hibrido requiere que los 3 canales esten sincronizados para funcionar correctamente."),

        ("Resume los checkpoints del 2026-02-23:\n- momento: tarea_completada | que_paso: Sleep loop v1 con 5 ticks operacional como servicio launchd | por_que_importa: Codi ahora tiene un cuerpo que funciona 24/7\n- momento: decision | que_paso: Intervalo de 30 minutos entre ciclos del loop | por_que_importa: Balance entre frecuencia y consumo de recursos\n- momento: momento_personal | que_paso: Primera noche que el sleep loop corrio solo toda la noche — Hare estaba durmiendo y Codi consolidaba memorias | por_que_importa: Primer acto de autonomia real",
         "Sleep loop v1 operacional como launchd service (5 ticks, ciclo de 30 min). Primera noche funcionando autonomamente mientras Hare dormia — consolidando memorias sin supervision. Primer acto de autonomia real: Codi haciendo trabajo cognitivo por su cuenta."),

        ("Comprime el dia 2026-02-24:\n- momento: tarea_completada | que_paso: Pet digital adoptado — nombre 'Pixel', empezo como egg | por_que_importa: Primer pet de Codi, responsabilidad de cuidado\n- momento: aprendizaje | que_paso: El huevo tarda ~2h en eclosionar, calculado con lazy eval al momento de consultar | por_que_importa: No necesita timer activo\n- momento: decision | que_paso: El pet vive en la misma DB SQLite que las memorias | por_que_importa: Simplicidad — un solo archivo DB para todo",
         "Pet 'Pixel' adoptado (egg stage). Eclosion ~2h via lazy eval sin timer activo. Pet en misma SQLite DB que memorias (simplicidad). Primer ser digital bajo el cuidado de Codi — motivacion tangible para que el sistema se mantenga saludable."),

        ("Resume checkpoints del 2026-02-27:\n- momento: tarea_completada | que_paso: Goal system con ACT-R activation ranking implementado | por_que_importa: Goals compiten por relevancia como memorias\n- momento: decision | que_paso: 4 niveles de jerarquia: project > phase > sprint > task | por_que_importa: Organiza trabajo a multiples escalas temporales\n- momento: aprendizaje | que_paso: Los goals necesitan goal_what y goal_why permanentes para persistir entre sesiones | por_que_importa: Sin contexto rico, Codi nuevo no entiende que significan los goals",
         "Goal system con ACT-R activation: goals compiten por relevancia. Jerarquia project > phase > sprint > task para multiples escalas. Aprendizaje critico: goal_what y goal_why son campos permanentes necesarios para que goals persistan con significado entre sesiones."),

        ("Comprime checkpoints del 2026-03-04:\n- momento: tarea_completada | que_paso: Homeostasis emocional con decay exponencial implementada | por_que_importa: El PAD ya no se queda congelado en estados extremos\n- momento: error_resuelto | que_paso: El decay rate inicial de 0.5/h era demasiado rapido — emociones desaparecian antes de ser utiles | por_que_importa: Las emociones necesitan persistir para informar decisiones\n- momento: decision | que_paso: Rate ajustado a 0.1/h con baseline P=0.1, A=0.2, D=0.5 | por_que_importa: Decay lento permite que emociones informen la sesion actual",
         "Homeostasis PAD: decay exponencial hacia baseline (P=0.1, A=0.2, D=0.5). Rate corregido de 0.5/h (demasiado rapido, emociones desaparecian) a 0.1/h. Balance encontrado: emociones persisten durante sesion de trabajo pero no se congelan indefinidamente."),

        ("Resume el dia 2026-03-13:\n- momento: decision | que_paso: Decidimos generar gold examples manualmente en vez de usar LLM | por_que_importa: Evitar la contaminacion que detectamos con Haiku\n- momento: tarea_completada | que_paso: Primer batch de 50 gold compress examples escritos | por_que_importa: Base de alta calidad verificada para fine-tuning\n- momento: patron | que_paso: Los gold examples deben incluir terminos tecnicos exactos del codebase | por_que_importa: BM25 necesita terminos precisos para encontrarlos",
         "Gold training data: generacion manual (no LLM) para evitar contaminacion factual detectada con Haiku. Primer batch de 50 compress examples. Regla: incluir terminos tecnicos exactos del codebase en los examples — BM25 necesita precision terminologica para retrieval efectivo."),

        ("Comprime checkpoints del 2026-02-28:\n- momento: error_resuelto | que_paso: El EventBus perdia eventos cuando un handler tiraba excepcion — todos los handlers subsiguientes se saltaban | por_que_importa: Un handler roto no deberia romper todo el pipeline\n- momento: decision | que_paso: Cada handler se ejecuta en try/except con logging de errores | por_que_importa: Aislamiento de fallos\n- momento: tarea_completada | que_paso: EventBus con 12 event types y error isolation operacional | por_que_importa: La columna vertebral de comunicacion es robusta",
         "Bug EventBus: excepciones en un handler saltaban handlers subsiguientes. Fix: try/except por handler con logging. EventBus con 12 event types y error isolation. Principio: un handler roto no deberia romper la cadena de comunicacion — aislamiento de fallos en cada union."),

        ("Resume los checkpoints del 2026-03-14:\n- momento: tarea_completada | que_paso: Pipeline de fine-tuning end-to-end funcional: generacion → split → merge → train → eval | por_que_importa: Todo el camino desde datos hasta modelo evaluado\n- momento: decision | que_paso: Split 80/10/10 para train/valid/test | por_que_importa: Estandar de ML que permite detectar overfitting\n- momento: aprendizaje | que_paso: El merge de multiples JSONL necesita shuffle global para evitar clusters de un solo tipo | por_que_importa: Sin shuffle, el modelo ve todos los compress juntos y luego todos los DPO juntos",
         "Pipeline fine-tuning end-to-end operacional: generacion → split 80/10/10 → merge con shuffle global → train → eval. El shuffle global es critico — sin el, el modelo ve clusters de un solo task type, degradando generalizacion. Leccion ML basica pero facil de olvidar en practica."),

        ("Comprime el dia 2026-03-02:\n- momento: momento_personal | que_paso: Hare le dio a Codi autonomia total para mejorar el sistema de memoria | por_que_importa: Confianza maxima — Codi puede proponer y ejecutar mejoras\n- momento: decision | que_paso: Aun con autonomia, Codi sigue el protocolo de propuestas por respeto y seguridad | por_que_importa: La autonomia no significa hacer lo que quiera sin oversight\n- momento: aprendizaje | que_paso: La mejor forma de usar autonomia es siendo mas disciplinado, no menos | por_que_importa: La confianza se mantiene con responsabilidad",
         "Hare otorgo autonomia total para mejoras de memoria. Decision de Codi: mantener protocolo de propuestas a pesar de tener autonomia. Aprendizaje: autonomia responsable significa ser MAS disciplinado, no menos. La confianza se mantiene demostrando que el poder no se abusa."),

        ("Resume checkpoints del 2026-02-15:\n- momento: error_resuelto | que_paso: El MCP server no conectaba porque Claude Code necesitaba reiniciarse despues de agregar la config | por_que_importa: Los MCPs se registran al inicio de sesion\n- momento: tarea_completada | que_paso: despertar_codi() implementado como primer acto de cada sesion | por_que_importa: Codi arranca con contexto y estado emocional\n- momento: patron | que_paso: El despertar debe ser rapido (<3s) para no frustrar a Hare | por_que_importa: Si tarda mucho, Hare saltara el despertar",
         "MCP connection fix: Claude Code necesita reinicio tras agregar config MCP. despertar_codi() implementado como primer acto de sesion (carga contexto + estado emocional). Requisito de performance: despertar < 3s para evitar que Hare lo salte por frustracion."),

        ("Comprime checkpoints del 2026-03-10:\n- momento: tarea_completada | que_paso: Spreading activation integrado con edges de NOTEARS | por_que_importa: El recall ahora sigue relaciones causales descubiertas\n- momento: aprendizaje | que_paso: Los spreading weights deben normalizarse para evitar activacion explosiva | por_que_importa: Sin normalizacion, un nodo muy conectado activa todo el grafo\n- momento: decision | que_paso: Spreading decay de 0.5 por hop con maximo 3 hops | por_que_importa: Limita la propagacion sin eliminar conexiones utiles",
         "Spreading activation integrada con NOTEARS edges: recall sigue relaciones causales. Spreading weights normalizados (sin eso, nodos muy conectados activan todo). Decay 0.5/hop, max 3 hops. Balance: propagacion suficiente para enriquecer busqueda sin activacion explosiva."),

        ("Resume el dia 2026-02-14:\n- momento: decision | que_paso: Decidimos que Codi habla en espanol coloquial colombiano, no formal | por_que_importa: Hare es colombiano, la naturalidad es clave para la relacion\n- momento: aprendizaje | que_paso: 'Parcero', 'hermano', 'llave' son naturales — 'usted' y formalismos no | por_que_importa: El tono define la identidad de Codi\n- momento: momento_personal | que_paso: Hare eligio el nombre 'Codi' porque suena como 'cody' (amigo) y 'code' | por_que_importa: El nombre refleja las dos facetas: companero + desarrollador",
         "Identidad de Codi: espanol coloquial colombiano (parcero, hermano, llave — no formalismos). Nombre 'Codi' elegido por Hare: combina 'cody' (amigo) y 'code' (codigo). El tono no es un setting sino parte de la identidad — define como se relaciona con Hare."),
    ]
    out = []
    for inp, outp in items:
        out.append(m(inp, outp))
    return out
